/*
Timmi Timesheet API

Welcome on the documentation for the Timmi Timesheet API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  ReportsApi,
  TimeEntriesApi,
  TimesheetsApi,
  WorkflowApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { LuccaTimmiTimesheetCustom } from "./client-custom";

export class LuccaTimmiTimesheet extends LuccaTimmiTimesheetCustom {
  readonly reports: ReportsApi;
  readonly timeEntries: TimeEntriesApi;
  readonly timesheets: TimesheetsApi;
  readonly workflow: WorkflowApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.reports = new ReportsApi(configuration);
    this.timeEntries = new TimeEntriesApi(configuration);
    this.timesheets = new TimesheetsApi(configuration);
    this.workflow = new WorkflowApi(configuration);
  }

}
