/*
Timmi Timesheet API

Welcome on the documentation for the Timmi Timesheet API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * You can [read more about this resource here](reference/Organization-v3.yaml/components/schemas/AxisSection).
 * @export
 * @interface AxisSection
 */
export interface AxisSection {
    /**
     * 
     * @type {string}
     * @memberof AxisSection
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof AxisSection
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof AxisSection
     */
    'code'?: string;
    /**
     * 
     * @type {string}
     * @memberof AxisSection
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof AxisSection
     */
    'multilingualName'?: string;
    /**
     * 
     * @type {number}
     * @memberof AxisSection
     */
    'ownerId'?: number;
    /**
     * 
     * @type {string}
     * @memberof AxisSection
     */
    'startOn'?: string;
    /**
     * 
     * @type {string}
     * @memberof AxisSection
     */
    'endOn'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AxisSection
     */
    'active'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof AxisSection
     */
    'axisId'?: number;
    /**
     * 
     * @type {Array<AxisSection>}
     * @memberof AxisSection
     */
    'parentAxisSections'?: Array<AxisSection>;
    /**
     * 
     * @type {Array<AxisSection>}
     * @memberof AxisSection
     */
    'childrenAxisSections'?: Array<AxisSection>;
}

