/*
Timmi Timesheet API

Welcome on the documentation for the Timmi Timesheet API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ReportColumnsInner } from './report-columns-inner';
import { ReportFiltersInner } from './report-filters-inner';

/**
 * ## Status  The generation of a report content is a background process. As long as this process is not complete, the report status stays `pending`. Once the report is complete, its status is set to `done`. May an error be encountered while generating its content, then its status is set to `error`.  The report content can only be viewed and downloaded once it is `done`.  ## Start & end dates  Start `startsOn` and end `endsOn` dates can be left `null`. In this case, default dates from the report-template are applied.  ## Filters  Filters are usually set in the report-template. But these can be overriden for a given report.  ## Fields
 * @export
 * @interface Report
 */
export interface Report {
    /**
     * 
     * @type {number}
     * @memberof Report
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Report
     */
    'status'?: ReportStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Report
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Report
     */
    'templateId': string;
    /**
     * 
     * @type {string}
     * @memberof Report
     */
    'startsOn'?: string;
    /**
     * 
     * @type {string}
     * @memberof Report
     */
    'endsOn'?: string;
    /**
     * 
     * @type {Array<ReportFiltersInner>}
     * @memberof Report
     */
    'filters'?: Array<ReportFiltersInner>;
    /**
     * 
     * @type {Array<ReportColumnsInner>}
     * @memberof Report
     */
    'columns'?: Array<ReportColumnsInner>;
}

type ReportStatusEnum = 'pending' | 'done' | 'error'


