/*
Timmi Timesheet API

Welcome on the documentation for the Timmi Timesheet API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ReportFiltersInner
 */
export interface ReportFiltersInner {
    /**
     * 
     * @type {string}
     * @memberof ReportFiltersInner
     */
    'kind'?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof ReportFiltersInner
     */
    'values'?: Array<number>;
}

