/*
Timmi Timesheet API

Welcome on the documentation for the Timmi Timesheet API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ReportColumnsInner
 */
export interface ReportColumnsInner {
    /**
     * 
     * @type {string}
     * @memberof ReportColumnsInner
     */
    'kind'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReportColumnsInner
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReportColumnsInner
     */
    'category'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ReportColumnsInner
     */
    'isRequired'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ReportColumnsInner
     */
    'isDefault'?: boolean;
    /**
     * Periodic columns will be duplicated as many times as there are occurrences of periodicity in the report.
     * @type {boolean}
     * @memberof ReportColumnsInner
     */
    'isPeriodic'?: boolean;
}

