/*
Timmi Timesheet API

Welcome on the documentation for the Timmi Timesheet API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AxisSection } from './axis-section';
import { TimeEntriesCreateMultipleResponseDataOneOf } from './time-entries-create-multiple-response-data-one-of';
import { TimeEntry } from './time-entry';
import { TimeEntryComment } from './time-entry-comment';

/**
 * @type TimeEntriesCreateMultipleResponseData
 * @export
 */
export type TimeEntriesCreateMultipleResponseData = TimeEntriesCreateMultipleResponseDataOneOf | TimeEntry;


