/*
Timmi Timesheet API

Welcome on the documentation for the Timmi Timesheet API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AxisSection } from './axis-section';
import { TimeEntry } from './time-entry';
import { TimeEntryComment } from './time-entry-comment';

/**
 * @type TimeEntriesCreateMultipleRequest
 * @export
 */
export type TimeEntriesCreateMultipleRequest = Array<TimeEntry> | TimeEntry;


