/*
Timmi Timesheet API

Welcome on the documentation for the Timmi Timesheet API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TimesheetsListResponseData } from './timesheets-list-response-data';

/**
 * 
 * @export
 * @interface TimesheetsListDueResponse
 */
export interface TimesheetsListDueResponse {
    /**
     * 
     * @type {TimesheetsListResponseData}
     * @memberof TimesheetsListDueResponse
     */
    'data'?: TimesheetsListResponseData;
}

