/*
Timmi Timesheet API

Welcome on the documentation for the Timmi Timesheet API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TimeEntriesDeleteMultipleResponse
 */
export interface TimeEntriesDeleteMultipleResponse {
    /**
     * HTTP status code.
     * @type {number}
     * @memberof TimeEntriesDeleteMultipleResponse
     */
    'Status'?: number;
    /**
     * Human readable error message.
     * @type {string}
     * @memberof TimeEntriesDeleteMultipleResponse
     */
    'Message'?: string;
}

