/*
Timmi Timesheet API

Welcome on the documentation for the Timmi Timesheet API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TimesheetOwner } from './timesheet-owner';

/**
 * ## Definitions  Timesheets are TimeEntries containers. A timesheet belongs to a single user `owner` and ranges over several days `[startsOn - endsOn[` (endsOn excluded). Its range depends on the submission frequency set up in Timmi Timesheet (weekly / monthly).  A timesheet purpose is to ease the approval workflow: rather than approving each TimeEntry individually, they are approved in a weekly / monthly batch.  The approval workflow looks like this:  ![Timmi Timesheet - Approval workflow](https://stoplight.io/api/v1/projects/cHJqOjEwNjgxNg/images/xfjxCP2RUa4)  Thus, a timesheet: - is created upon submission ; - is \"pending approval\" (`status: 1`) as long as all approvers have not approved it ; - is \"approved\" (`status: 2`) once all approvers have approved it ; - may become \"rejected\" (`status: 3`) whenever:   - the submitter cancels the submission, which is possible as long as the timesheet is not fully approved ;   - one of the approvers denies the timesheet ;   - an administrator invalidates the timesheet, which is only possible once the timesheet is fully approved.  Once a timesheet is rejected, a new one has to be submitted and the workflow starts again.  ## Fields
 * @export
 * @interface Timesheet
 */
export interface Timesheet {
    /**
     * 
     * @type {string}
     * @memberof Timesheet
     */
    'id'?: string;
    /**
     * - 0: the timesheet is yet to be submitted - 1: the timesheet has been submitted and approval is still pending - 2: the timesheet has been submitted and approved. - 3: the timesheet has been rejected (cancelled after submission, denied upon approval or invalidated after having been approved) 
     * @type {number}
     * @memberof Timesheet
     */
    'status'?: TimesheetStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Timesheet
     */
    'startsOn'?: string;
    /**
     * 
     * @type {string}
     * @memberof Timesheet
     */
    'endsOn'?: string;
    /**
     * 
     * @type {number}
     * @memberof Timesheet
     */
    'ownerId'?: number;
    /**
     * 
     * @type {TimesheetOwner}
     * @memberof Timesheet
     */
    'owner'?: TimesheetOwner;
    /**
     * Identifier of the applicable \"statute\" (configuration).
     * @type {number}
     * @memberof Timesheet
     */
    'statuteId'?: number;
}

type TimesheetStatusEnum = 0 | 1 | 2 | 3


