/*
Timmi Timesheet API

Welcome on the documentation for the Timmi Timesheet API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Only used on activities (TimeEntries w/ AxisSections).
 * @export
 * @interface TimeEntryComment
 */
export interface TimeEntryComment {
    /**
     * 
     * @type {string}
     * @memberof TimeEntryComment
     */
    'content'?: string;
    /**
     * 
     * @type {number}
     * @memberof TimeEntryComment
     */
    'authorId'?: number;
    /**
     * 
     * @type {string}
     * @memberof TimeEntryComment
     */
    'createdAt'?: string;
}

