/*
Timmi Timesheet API

Welcome on the documentation for the Timmi Timesheet API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TimeEntriesCreateMultipleResponseData } from './time-entries-create-multiple-response-data';

/**
 * 
 * @export
 * @interface TimeEntriesUpdateMultipleResponse
 */
export interface TimeEntriesUpdateMultipleResponse {
    /**
     * 
     * @type {TimeEntriesCreateMultipleResponseData}
     * @memberof TimeEntriesUpdateMultipleResponse
     */
    'data'?: TimeEntriesCreateMultipleResponseData;
}

