/*
Timmi Timesheet API

Welcome on the documentation for the Timmi Timesheet API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TimesheetUser
 */
export interface TimesheetUser {
    /**
     * Unique identifier of this User.
     * @type {number}
     * @memberof TimesheetUser
     */
    'id'?: number;
    /**
     * Given name.
     * @type {string}
     * @memberof TimesheetUser
     */
    'firstName'?: string;
    /**
     * Family name
     * @type {string}
     * @memberof TimesheetUser
     */
    'lastName'?: string;
    /**
     * Email address.
     * @type {string}
     * @memberof TimesheetUser
     */
    'mail'?: string;
    /**
     * Unique identifier of the legal establishment this user currently has a work contract with.
     * @type {number}
     * @memberof TimesheetUser
     */
    'legalEntityId'?: number;
}

