/*
Timmi Timesheet API

Welcome on the documentation for the Timmi Timesheet API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TimeEntry } from './time-entry';

/**
 * 
 * @export
 * @interface TimeEntriesListTimeEntriesResponseData
 */
export interface TimeEntriesListTimeEntriesResponseData {
    /**
     * 
     * @type {number}
     * @memberof TimeEntriesListTimeEntriesResponseData
     */
    'count'?: number;
    /**
     * 
     * @type {Array<TimeEntry>}
     * @memberof TimeEntriesListTimeEntriesResponseData
     */
    'items'?: Array<TimeEntry>;
}

