/*
Timmi Timesheet API

Welcome on the documentation for the Timmi Timesheet API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Transfer defines a change in pay\'s element distribution
 * @export
 * @interface Transfer
 */
export interface Transfer {
    /**
     * Unique identifier of the associated transfer authorization.
     * @type {number}
     * @memberof Transfer
     */
    'transferAuthorizationId'?: number;
    /**
     * Format: d.hh:mm:ss. Max: \"1.00:00:00\" (ie 24 hours).
     * @type {string}
     * @memberof Transfer
     */
    'amount'?: string;
    /**
     * 
     * @type {string}
     * @memberof Transfer
     */
    'comment'?: string;
}

