/*
Timmi Timesheet API

Welcome on the documentation for the Timmi Timesheet API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WorkflowCancelTimesheetByIdRequestTimesheetsInner } from './workflow-cancel-timesheet-by-id-request-timesheets-inner';

/**
 * 
 * @export
 * @interface WorkflowCancelTimesheetByIdRequest
 */
export interface WorkflowCancelTimesheetByIdRequest {
    /**
     * 
     * @type {Array<WorkflowCancelTimesheetByIdRequestTimesheetsInner>}
     * @memberof WorkflowCancelTimesheetByIdRequest
     */
    'timesheets'?: Array<WorkflowCancelTimesheetByIdRequestTimesheetsInner>;
}

