/*
Timmi Timesheet API

Welcome on the documentation for the Timmi Timesheet API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface WorkflowApproveTimesheetsByIdRequestTimesheetsInner
 */
export interface WorkflowApproveTimesheetsByIdRequestTimesheetsInner {
    /**
     * 
     * @type {number}
     * @memberof WorkflowApproveTimesheetsByIdRequestTimesheetsInner
     */
    'id': number;
    /**
     * 
     * @type {Array<any>}
     * @memberof WorkflowApproveTimesheetsByIdRequestTimesheetsInner
     */
    'transfers'?: Array<any>;
}

