/*
Timmi Timesheet API

Welcome on the documentation for the Timmi Timesheet API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface WorkflowSendReminderEmailRequestTimesheetsInner
 */
export interface WorkflowSendReminderEmailRequestTimesheetsInner {
    /**
     * 
     * @type {string}
     * @memberof WorkflowSendReminderEmailRequestTimesheetsInner
     */
    'startsAt': string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowSendReminderEmailRequestTimesheetsInner
     */
    'endsAt': string;
    /**
     * 
     * @type {number}
     * @memberof WorkflowSendReminderEmailRequestTimesheetsInner
     */
    'ownerId': number;
    /**
     * 
     * @type {string}
     * @memberof WorkflowSendReminderEmailRequestTimesheetsInner
     */
    'comment'?: string;
}

