/*
Timmi Timesheet API

Welcome on the documentation for the Timmi Timesheet API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WorkflowSubmitTimesheetRequestTimesheetsInner } from './workflow-submit-timesheet-request-timesheets-inner';

/**
 * 
 * @export
 * @interface WorkflowSubmitTimesheetRequest
 */
export interface WorkflowSubmitTimesheetRequest {
    /**
     * 
     * @type {Array<WorkflowSubmitTimesheetRequestTimesheetsInner>}
     * @memberof WorkflowSubmitTimesheetRequest
     */
    'timesheets'?: Array<WorkflowSubmitTimesheetRequestTimesheetsInner>;
}

