/*
Timmi Timesheet API

Welcome on the documentation for the Timmi Timesheet API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface WorkflowSendReminderEmailResponseItemsInner
 */
export interface WorkflowSendReminderEmailResponseItemsInner {
    /**
     * 
     * @type {number}
     * @memberof WorkflowSendReminderEmailResponseItemsInner
     */
    'Id'?: number;
    /**
     * 
     * @type {string}
     * @memberof WorkflowSendReminderEmailResponseItemsInner
     */
    'ExceptionMessage'?: string;
    /**
     * 
     * @type {number}
     * @memberof WorkflowSendReminderEmailResponseItemsInner
     */
    'Status'?: WorkflowSendReminderEmailResponseItemsInnerStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof WorkflowSendReminderEmailResponseItemsInner
     */
    'Title'?: string;
    /**
     * URL of the relevant timesheet.
     * @type {string}
     * @memberof WorkflowSendReminderEmailResponseItemsInner
     */
    'Url'?: string;
}

type WorkflowSendReminderEmailResponseItemsInnerStatusEnum = 0


