/*
Timmi Timesheet API

Welcome on the documentation for the Timmi Timesheet API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Transfer } from './transfer';

/**
 * 
 * @export
 * @interface WorkflowSubmitTimesheetRequestTimesheetsInner
 */
export interface WorkflowSubmitTimesheetRequestTimesheetsInner {
    /**
     * 
     * @type {string}
     * @memberof WorkflowSubmitTimesheetRequestTimesheetsInner
     */
    'startsAt': string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowSubmitTimesheetRequestTimesheetsInner
     */
    'endsAt': string;
    /**
     * 
     * @type {number}
     * @memberof WorkflowSubmitTimesheetRequestTimesheetsInner
     */
    'ownerId': number;
    /**
     * 
     * @type {Array<Transfer>}
     * @memberof WorkflowSubmitTimesheetRequestTimesheetsInner
     */
    'transfers'?: Array<Transfer>;
}

