/*
Timmi Timesheet API

Welcome on the documentation for the Timmi Timesheet API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WorkflowApproveTimesheetsByIdRequestTimesheetsInner } from './workflow-approve-timesheets-by-id-request-timesheets-inner';

/**
 * 
 * @export
 * @interface WorkflowApproveTimesheetsByIdRequest
 */
export interface WorkflowApproveTimesheetsByIdRequest {
    /**
     * 
     * @type {Array<WorkflowApproveTimesheetsByIdRequestTimesheetsInner>}
     * @memberof WorkflowApproveTimesheetsByIdRequest
     */
    'timesheets'?: Array<WorkflowApproveTimesheetsByIdRequestTimesheetsInner>;
}

